### ISSUE TITLE
I'm definitely interested in this project, but no gem found in any repo

### ISSUE THREAD

**Issue by jakeatwork** [silvermind/rack-utm#1]
On `gem install rack-utm`, I get:

ERROR:  Could not find a valid gem 'rack-utm' (>= 0) in any repository
ERROR:  Possible alternatives: rack-auth, rack-gcm, rack-lti, rack-ntlm, racket

**Comment by jakeatwork** [comment]
I just forked this and installed it from my github repo directly in my gem file. It's working fine. Thanks.

**Comment by silvermind** [comment]
@jakeatwork thanks for the ping, need to register it with rubygems. hope it helps :+1:

**Comment by duksis** [comment]
@silvermind I had the same issue and allowed myself to publish it for you - hope you don't mind 
https://rubygems.org/gems/rack-utm

thanks for the gem!
